### ISSUE TITLE
Downloaded tgz is not readable/recognized as tar archive

### ISSUE THREAD

**Issue by hgheady** [hafbau/goat_upload#1]
Thanks for your work on this, Hafiz!

I have tried downloading some existing archives (e.g. `test100MB.tgz`), as well as an archive I created and uploaded (`test0602.tgz`), and in all cases, the downloaded file can't be read/uncompressed on my mac.
```
%> tar -xvf test100MB.tgz
tar: Error opening archive: Unrecognized archive format
```
I see the same output when attempting to open in the GUI: "Unable to expand "test100MB.tgz". It is in an unsupported format."

Here is the output of the `file` command on the archive I created locally, before upload:
```
%> file test_files/test0602.tgz
test_files/test0602.tgz: POSIX tar archive
```
and after downloading:
```
%> file test0602.tgz
test0602.tgz: data
```

I see this result after downloading the file via curl, wget, and the browser.

**Comment by hafbau** [comment]
Thank you for this opportunity and for finding this bug.
